name: Update Correlation Data

on:
  schedule:
    - cron: '0 0 */4 * *'  # Runs every 4 days at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.1.4 requests==2.31.0 python-dotenv==1.0.0 tqdm==4.66.1

      - name: Create .env file
        run: |
          echo "COINGECKO_API_KEY=${{ secrets.COINGECKO_API_KEY }}" > .env

      - name: Run correlation script
        run: python crypto_correlation.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add crypto_correlations_*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update correlation data [skip ci]" && git push) 
