name: Update Correlation Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r assets/requirements.txt

      - name: Create .env file
        run: |
          echo "COINGECKO_API_KEY=${{ secrets.COINGECKO_API_KEY }}" > .env

      - name: Run correlation script
        run: python assets/crypto_correlation.py

      - name: Move CSV files to assets
        run: |
          mv crypto_correlations_*.csv assets/

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/crypto_correlations_*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update correlation data [skip ci]" && git push) 